version: '1.0'
services:

  app:
    image: web
    container_name: backend-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    container_name: backend-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:17
    container_name: backend-og
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'pass321!'
      POSTGRES_DB: 'web'
      POSTGRES_USER: 'web'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
